using PetCare.Core;
using System.Text;
using System.Linq;

namespace PetCare.BE;

/// <summary>
/// GameLog - Implementation of game logging service for PetCare chat history and event management
/// 
/// This class provides comprehensive logging functionality for the PetCare virtual pet game,
/// managing all chat interactions, AI responses, and game events. It extends the BaseDataObject
/// to inherit persistence capabilities while implementing IGameLog for standardized logging operations.
/// 
/// Key Features:
/// - Persistent storage of all chat interactions and game events
/// - Support for multiple chat categories (user chat, game events, system messages)
/// - Formatted text generation for UI display purposes
/// - Chronological filtering and retrieval of log entries
/// - JSON-based data persistence through inheritance
/// - Thread-safe operations for concurrent access scenarios
/// 
/// Data Management:
/// - Stores complete conversation history for AI context continuity
/// - Maintains metadata for each interaction (timestamps, categories, prompts)
/// - Provides formatted output for chat display in user interface
/// - Supports filtering by chat category for specific interaction types
/// - Handles both simple text logging and complex structured log entries
/// 
/// The GameLog serves as the central repository for all game narrative and maintains
/// the conversational context that allows the AI to provide consistent, contextually
/// appropriate responses throughout the game experience.
/// </summary>
public class GameLog : BaseDataObject<List<GameLogEntry>>, IGameLog
{
    #region Constructor and Initialization
    
    /// <summary>
    /// Initializes a new GameLog instance with persistent storage configuration
    /// 
    /// Sets up the game log with automatic JSON persistence to the specified file.
    /// The base class handles file operations, serialization, and data management,
    /// while this class provides game-specific logging functionality.
    /// 
    /// The log data is stored as a List&lt;GameLogEntry&gt; and persisted to
    /// "log_data.json" in the application's data directory for cross-session continuity.
    /// </summary>
    public GameLog() : base("log_data.json")
    {
        // Initialization handled by base class constructor
        // Base class sets up JSON persistence and data object management
    }
    
    #endregion

    #region Data Access Properties
    
    /// <summary>
    /// Gets the complete list of log entries for direct access and manipulation
    /// 
    /// Provides access to the underlying data collection for scenarios requiring
    /// direct manipulation of log entries, bulk operations, or advanced filtering.
    /// 
    /// The entries are stored chronologically and include all interaction types:
    /// - User chat messages and AI responses
    /// - Game event notifications and system messages
    /// - Action confirmations and stat change notifications
    /// - Error messages and debug information
    /// 
    /// Direct access should be used carefully to maintain data integrity.
    /// </summary>
    /// <value>
    /// List&lt;GameLogEntry&gt; containing all logged interactions and events
    /// </value>
    public List<GameLogEntry> Entries => base.DataObj;
    
    #endregion

    #region Simple Text Logging Methods
    
    /// <summary>
    /// Adds a simple system message with associated user prompt to the game log
    /// 
    /// Creates a basic log entry for system-generated messages that have an
    /// associated user action or prompt. Automatically categorizes the entry
    /// as a system message and timestamps it for chronological ordering.
    /// 
    /// This method is useful for logging game events that result from player
    /// actions but are generated by the system rather than the AI model.
    /// </summary>
    /// <param name="message">
    /// System-generated message content to log (e.g., "Game saved successfully")
    /// </param>
    /// <param name="userPrompt">
    /// Associated user action or prompt that triggered this message
    /// (e.g., "Player clicked save button")
    /// </param>
    public void Add(string message, string userPrompt)
    {
        DataObj.Add(new GameLogEntry(message, userPrompt) { ChatId = ChatIdEnum.System });
    }

    /// <summary>
    /// Adds a simple system message without an associated user prompt
    /// 
    /// Creates a basic log entry for standalone system messages that don't
    /// have a specific user action trigger. Useful for autonomous system
    /// events, error messages, or informational notifications.
    /// 
    /// The entry is automatically categorized as a system message with an
    /// empty user prompt field to maintain data structure consistency.
    /// </summary>
    /// <param name="message">
    /// System message content to log (e.g., "Daily stat decay applied")
    /// </param>
    public void Add(string message)
    {
        DataObj.Add(new GameLogEntry(message, string.Empty) { ChatId = ChatIdEnum.System });
    }
    
    #endregion

    #region Structured Logging Methods
    
    /// <summary>
    /// Adds a complete structured log entry with full metadata
    /// 
    /// Adds a fully-formed GameLogEntry object to the log, preserving all
    /// metadata including chat categories, timestamps, system prompts, and
    /// user context. This is the primary method used by the AI model and
    /// other complex systems for comprehensive interaction logging.
    /// 
    /// This method maintains the complete context needed for AI conversation
    /// continuity and provides full audit trails for debugging and analysis.
    /// </summary>
    /// <param name="entry">
    /// Complete GameLogEntry object containing message, metadata, timestamps,
    /// chat category, system prompts, and user context information
    /// </param>
    /// <exception cref="ArgumentNullException">Thrown when entry is null</exception>
    public void Add(GameLogEntry entry)
    {
        DataObj.Add(entry);
    }
    
    #endregion

    #region Formatted Output Methods
    
    /// <summary>
    /// Generates formatted text representation of the complete chat log for UI display
    /// 
    /// Creates a human-readable string containing the entire conversation history
    /// formatted for display in the game's chat interface. The output presents
    /// conversations in a natural "Owner/Pet" dialog format that's intuitive
    /// for players to follow.
    /// 
    /// Format Structure:
    /// - "Owner: [User Prompt]" - Shows what the player did or said
    /// - "Pet: [AI Response]" - Shows the pet's reaction or response
    /// - Double line breaks between interactions for readability
    /// 
    /// The method processes all log entries chronologically to maintain
    /// conversation flow and narrative coherence. Empty or null prompts
    /// are handled gracefully to prevent formatting issues.
    /// 
    /// This formatted output is used directly by the UI to display the chat
    /// history and provide players with context for ongoing conversations.
    /// </summary>
    /// <returns>
    /// Formatted string containing the complete conversation history ready
    /// for display in chat UI components
    /// </returns>
    public string GetLogText()
    {
        StringBuilder log_string = new();
        
        // Process each log entry in chronological order
        foreach (var entry in DataObj)
        {
            // Add user prompt line (what the owner did/said)
            log_string.AppendLine("Owner: " + entry.UserPrompt + "\n");
            
            // Add AI response line (what the pet responded)
            log_string.AppendLine($"Pet:" + entry.Message + "\n");
        }
        
        return log_string.ToString();
    }
    
    #endregion

    #region Filtered Retrieval Methods
    
    /// <summary>
    /// Retrieves log entries filtered by chat category and sorted by timestamp
    /// 
    /// Provides filtered access to log entries based on their chat category,
    /// allowing systems to retrieve specific types of interactions. Results
    /// are sorted in descending chronological order (most recent first) for
    /// scenarios where recent context is most important.
    /// 
    /// Common use cases:
    /// - Retrieving only user chat messages for AI context
    /// - Getting game event logs for debugging
    /// - Filtering system messages for audit trails
    /// - Extracting specific interaction types for analysis
    /// 
    /// The filtering maintains all original metadata while providing focused
    /// access to relevant interaction subsets.
    /// </summary>
    /// <param name="chatId">
    /// Chat category to filter by (UserChat, GameMessageLog, System, etc.)
    /// Only entries matching this category will be returned
    /// </param>
    /// <returns>
    /// List&lt;GameLogEntry&gt; containing filtered entries sorted by timestamp
    /// in descending order (most recent first)
    /// </returns>
    public List<GameLogEntry> GetChatLog(ChatIdEnum chatId)
    {
        return DataObj
            .Where(entry => entry.ChatId == chatId)      // Filter by chat category
            .OrderByDescending(o => o.MessageTime)       // Sort by timestamp (newest first)
            .ToList();                                    // Convert to list for return
    }
    
    #endregion
}


