<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>PetCare.BE</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\PetCare-Core\PetCare-Core.csproj" />
    <ProjectReference Include="..\PetCare-AI\PetCare-AI.csproj" />
	<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.120" />
  </ItemGroup>

</Project>
